package com.derteuffel.school.enums;

/**
 * Created by user on 03/04/2020.
 */
public enum ENiveau {
    PREMIERE_PRIMAIRE,
    DEUXIEME_PRIMAIRE,
    TROISIEME_PRIMAIRE,
    QUATRIEME_PRIMAIRE,
    CINQUIEME_PRIMAIRE,
    SIXIEME_PRIMAIRE,
    PREMIERE_SECONDAIRE,
    DEUXIEME_SECONDAIRE,
    TROISIEME_SECONDAIRE,
    QUATRIEME_SECONDAIRE,
    CINQUIEME_SECONDAIRE,
    SIXIEME_SECONDAIRE,
    SEPTIEME_SECONDAIRE,

}
